#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

readonly target=${1:?"usage: $0 <target>"}

while true; do
  inotifywait -e close_write -m --format '%f' /boot |
    while read file; do
      if [[ "${file}" == "intel-ucode.img" ]] ||
        [[ "${file}" == "initramfs-${target}.img" ]] ||
        [[ "${file}" == "initramfs-${target}-fallback.img" ]] ||
        [[ "${file}" == "vmlinuz-${target}" ]]; then
        echo "${file} changed"
        zfs-esp-sync "${target}"
      fi
    done
done
